backend:
  name: git-gateway
  branch: main # Cambia a la rama donde alojarás tu sitio (ej. master, main)

media_folder: "assets/uploads" # Carpeta donde se guardarán las imágenes subidas
public_folder: "/assets/uploads" # Ruta pública para acceder a las imágenes

collections:
  - name: "site_data"
    label: "Configuración Global del Sitio"
    files:
      - file: "_data/site_data.json"
        label: "Datos Generales"
        name: "general"
        fields:
          - {label: "Logo del Sitio", name: "logo_image", widget: "image", required: false, default: "https://placehold.co/60x60/02BF61/FFFFFF?text=LOGO"}
          - {label: "Título de la Sección Nosotros", name: "about_title", widget: "string", default: "U.E. COLEGIO 'SANTA BÁRBARA'"}
          - {label: "Título de la Sección Calendario", name: "calendar_title", widget: "string", default: "CALENDARIO ESCOLAR"}
          - {label: "Título de la Sección Oferta Académica", name: "offers_title", widget: "string", default: "NUESTRA OFERTA ACADÉMICA"}
          - {label: "Título de la Sección Historia", name: "history_title", widget: "string", default: "NUESTRA HISTORIA"}
          - {label: "Título del Formulario de Contacto", name: "form_contact_title", widget: "string", default: "Formulario de Contacto"}
          - {label: "Título de Información de Contacto", name: "contact_info_title", widget: "string", default: "Información de Contacto"}
          - {label: "Título de la Sección Ubicación", name: "location_title", widget: "string", default: "Nuestra Ubicación"}
          # Las entradas de contacto y mapa se han movido o eliminado de aquí.

  - name: "about_content"
    label: "Contenido - Sección Nosotros"
    files:
      - file: "_data/about.md"
        label: "Contenido de Nosotros"
        name: "about"
        fields:
          - {label: "Contenido (Markdown)", name: "body", widget: "markdown", default: "La **U.E. Colegio “Santa Bárbara”** es una institución educativa con una sólida trayectoria...\n\nNuestros objetivos principales son: fomentar el pensamiento crítico...\n\nBuscamos preparar a nuestros estudiantes para que sean ciudadanos activos..."}

  - name: "history_content"
    label: "Contenido - Sección Historia"
    files:
      - file: "_data/history.md"
        label: "Contenido de Historia"
        name: "history"
        fields:
          - {label: "Imagen de la Sección Historia", name: "section_image_history", widget: "image", required: false, default: "https://placehold.co/400x300/02BF61/FFFFFF?text=Fachada+Colegio"}
          - {label: "Contenido (Markdown)", name: "body", widget: "markdown", default: "Fundada en el año 1999 por la Licda. Evis Solvey Zabala Gutierrez y la Licda. Arelis Ardila Diaz...\n\nPosteriormente, en el año 2023, se integró el nivel de educación pre-escolar...\n\nSu dirección y gestión recaen en un equipo comprometido..."}

  - name: "news_list"
    label: "Noticias del Carrusel"
    files:
      - file: "_data/news.json"
        label: "Datos de Noticias"
        name: "news_config"
        fields:
          - label: "Lista de Noticias"
            name: "news"
            widget: "list"
            fields:
              - {label: "Título de la Noticia", name: "title", widget: "string"}
              - {label: "Descripción Breve", name: "description", widget: "text"}
              - {label: "Imagen de la Noticia", name: "image", widget: "image", required: false}

  - name: "offers_list"
    label: "Oferta Académica"
    files:
      - file: "_data/offers.json"
        label: "Datos de Ofertas"
        name: "offers_config"
        fields:
          - label: "Lista de Ofertas"
            name: "offers"
            widget: "list"
            fields:
              - {label: "Título de la Oferta", name: "title", widget: "string"}
              - {label: "Contenido de la Oferta", name: "content", widget: "text"}
              - {label: "Clase de Color Pastel", name: "color_class", widget: "select", options: ["pastel-yellow", "pastel-blue", "pastel-red"]}

  - name: "holidays_list"
    label: "Días Festivos (Calendario)"
    files:
      - file: "_data/holidays.json"
        label: "Datos de Días Festivos"
        name: "holidays_config"
        fields:
          - label: "Lista de Días Festivos"
            name: "holidays"
            widget: "list"
            fields:
              - {label: "Nombre del Festivo", name: "name", widget: "string"}
              - {label: "Día", name: "day", widget: "number", min: 1, max: 31}
              - {label: "Mes (1=Enero, 12=Diciembre)", name: "month", widget: "number", min: 1, max: 12}

  - name: "contact_section" # NUEVA COLECCIÓN
    label: "Datos de Contacto"
    files:
      - file: "_data/contact_data.json"
        label: "Información de Contacto General"
        name: "contact_details"
        fields:
          - {label: "Teléfono de Contacto", name: "contact_phone", widget: "string", default: "(0276) 343-3631"}
          - {label: "Dirección de Contacto", name: "contact_address", widget: "string", default: "Carrera. 10 con Calle 7, Casa #7-7, Centro, San Cristóbal, Edo. Táchira."}
          - {label: "Usuario de Instagram", name: "instagram_handle", widget: "string", default: "@colegio_santabarbara"}
          - {label: "URL de Instagram", name: "instagram_url", widget: "string", default: "https://www.instagram.com/colegio_santabarbara"}
